import { motion } from 'framer-motion'
import { FiArrowDown } from 'react-icons/fi'
import { ABOUT } from '../../data/content'
import GlassCard from '../ui/GlassCard'

export default function About() {
  return (
    <section id="about" className="section-padding relative bg-[#FFFBF5]">
      <div className="mx-auto grid max-w-7xl grid-cols-1 gap-16 lg:grid-cols-2 lg:gap-12">
        <div className="flex flex-col gap-6">
          <motion.span
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.5 }}
            className="eyebrow"
          >
            {ABOUT.eyebrow}
          </motion.span>

          <motion.h2
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.6, delay: 0.05 }}
            className="font-display text-3xl font-bold leading-tight text-[#1F2937] md:text-4xl"
          >
            {ABOUT.heading}
          </motion.h2>

          {ABOUT.paragraphs.map((paragraph, index) => (
            <motion.p
              key={paragraph}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-80px' }}
              transition={{ duration: 0.6, delay: 0.1 + index * 0.07 }}
              className="leading-relaxed text-[#5F5147]"
            >
              {paragraph}
            </motion.p>
          ))}
        </div>

        <GlassCard className="p-6 md:p-8" delay={0.1}>
          <p className="eyebrow mb-4">Text to CIF</p>

          <div className="rounded-2xl border border-[#E7D7C9] bg-[#1F2937] p-4 font-mono text-xs leading-relaxed text-[#FFD6A5]">
            <p>_cell_length_a&nbsp;&nbsp;10.3340</p>
            <p>_cell_length_b&nbsp;&nbsp;6.0110</p>
            <p>_cell_length_c&nbsp;&nbsp;4.6960</p>
            <p className="text-[#FF7A00]">_space_group_name&nbsp;&nbsp;Pnma</p>
            <p className="text-[#F7E7D5]">_atom_site_label&nbsp;&nbsp;Li1&nbsp;&nbsp;0.000&nbsp;0.000&nbsp;0.000</p>
          </div>

          <div className="my-4 flex items-center justify-center text-[#FF7A00]">
            <FiArrowDown className="animate-float-med" />
          </div>

          <div className="rounded-2xl border border-[#E7D7C9] bg-white p-4 text-sm leading-relaxed text-[#5F5147] shadow-sm">
            &ldquo;This lithium iron phosphate candidate uses an orthorhombic olivine-inspired cell and is ready
            for visualization, property prediction, and CIF download.&rdquo;
          </div>

          <p className="mt-4 font-mono text-xs text-[#8A7664]">Generated by the CrysText inference layer</p>
        </GlassCard>
      </div>
    </section>
  )
}
